name: Codeforces Auto-Commit

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies  # ✅ Install missing requests package
        run: pip install requests

      - name: Fetch recent Codeforces submissions
        run: |
          import requests
          import json
          import os
          from datetime import datetime

          # Your Codeforces handle
          HANDLE = "dummyDax"
          API_URL = f"https://codeforces.com/api/user.status?handle={HANDLE}&from=1&count=5"

          # Fetch submissions
          response = requests.get(API_URL)
          data = response.json()

          if data["status"] != "OK":
              print("Error fetching Codeforces data")
              exit(1)

          # Read stored submissions to avoid duplicates
          history_file = "submission_history.json"
          if os.path.exists(history_file):
              with open(history_file, "r") as f:
                  submitted_problems = json.load(f)
          else:
              submitted_problems = []

          new_submissions = []
          for submission in data["result"]:
              if submission["verdict"] == "OK":
                  problem_id = f"{submission['problem']['contestId']}_{submission['problem']['index']}"
                  if problem_id not in submitted_problems:
                      new_submissions.append(problem_id)
                      submitted_problems.append(problem_id)

          if not new_submissions:
              print("No new accepted solutions")
              exit(0)

          # Save updated history
          with open(history_file, "w") as f:
              json.dump(submitted_problems, f, indent=4)

          # ✅ Save problem IDs instead of source code (since CF API doesn't return source)
          log_file = "submissions/log.txt"
          os.makedirs("submissions", exist_ok=True)

          with open(log_file, "a") as f:
              for problem_id in new_submissions:
                  f.write(f"{problem_id} - Solved on {datetime.now()}\n")

          print(f"Logged {len(new_submissions)} new solved problems.")

        shell: python

      - name: Commit and push changes
        run: |
          git config --global user.name "GitDaksh"
          git config --global user.email "daksh.java.util@gmail.com"
          git add .
          git commit -m "Auto-commit Codeforces submissions $(date)" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
